### ISSUE TITLE
no gray line ver

### ISSUE THREAD

**Issue by 7planets** [fnick851/github-theme-for-browsers#1]
Could you make a version without the gray line under tabs?

**Comment by fnick851** [comment]
@7planets Could you provide a screenshot to explain? Also please tell me the OS, browser, browser version you are using. Thanks.

**Comment by 7planets** [comment]
win10, edge 90, its the active tab outline i guess 
https://i.imgur.com/O7wDt6Z.png

**Comment by fnick851** [comment]
@7planets 
I just pushed a new version.
